output_folder: output
data_folder: assets
exp_name: debug
ckpt: /path/to/DexLearn/dexlearn/ckpt/step_050000.pth      # ckpt path to load
resume: true

seed: 0
device: 'cuda:0'

##########################
# other config yamls
##########################

defaults:
  - _self_
  - algo: nflow
  - data: bodex_leap

data_name: ${hydra:runtime.choices.data}
algo_name: ${hydra:runtime.choices.algo}

hydra:
  run:
    dir: ${...output_folder}/${...data_name}_${...algo_name}_${...exp_name}
    

##########################
# wandb logging
##########################
wandb:
  folder: ${output_folder}
  group: ${algo_name}
  id: ${data_name}_${algo_name}_${exp_name}
  mode: online
  project: DexGraspLearn
  resume: ${resume}





